
name: ""
description: ""
url: "https://hpaluch.github.io/jekyll-bootstrap-assets"

exclude: [ "*.sh" , "*.swp", "README.md","Gemfile","Gemfile.lock" ]

gems:
  - jekyll-assets

assets:
  cdn: https://hpaluch.github.io/jekyll-bootstrap-assets
  compress:
    # do net mess with messy javascript files (thery are minified anyway)
    js: false
  assets:
   - "jquery.min.map"

show_ads: true
navigation:
  external:
     - url: http://getbootstrap.com/examples/blog/
       menuTitle: BlogTemplate
       title: Bootstrap Blog Template
     - url: http://getbootstrap.com
       menuTitle: Bootstrap
       title: Bootstrap homepage


