
name: ""
description: ""
url: "http://YOUR_SITE_URL"

exclude: [ "*.sh" , "*.swp", "README.md","Gemfile","Gemfile.lock" ]

gems:
  - jekyll-assets

assets:
  compress:
    # do net mess with messy javascript files (thery are minified anyway)
    js: false
  assets:
   - "jquery.min.map"

show_ads: true
navigation:
  external:
     - url: http://getbootstrap.com/examples/blog/
       menuTitle: BlogTemplate
       title: Bootstrap Blog Template
     - url: http://getbootstrap.com
       menuTitle: Bootstrap
       title: Bootstrap homepage


